### ISSUE TITLE
AMIが利用できない状況になっている

### ISSUE THREAD

**Issue by saboyutaka** [showwin/ISHOCON1#31]
現在, `ami-0d00b2a9a38084503` のAMIがAWS上で検索しても見つからない状況になっています。ISHOCONをISUCONの学習として利用できたらと思うのですが、今後公開する予定はありますか？

**Comment by showwin** [comment]
@saboyutaka お返事遅くなりました 🙏 
[こちらの影響](https://aws.amazon.com/jp/about-aws/whats-new/2022/03/amazon-machine-images-public-visibility-two-years/)をうけて、公開から2年を経過したためデフォルトでは見えないようになっていそうですね…

時間を見つけて中身が同じAMIを再作成しようと思いますが、取り急ぎの解決方法としては[こちらの手順](https://github.com/showwin/ISHOCON1/blob/master/terraform/README.md)に従ってTerraformで構築いただくと、deprecatedなAMIでも指定できるのでうまく動くのではと思います。

**Comment by showwin** [comment]
[v1.3](https://github.com/showwin/ISHOCON1/releases/tag/v1.3) のリリースに伴い、新たな AMI `ami-06cda439fc5c0da1b` を公開いたしました。
