### ISSUE TITLE
他言語で参考実装を作る時のガイドライン作成

### ISSUE THREAD

**Issue by showwin** [showwin/ISHOCON1#7]
>作問者が意図して遅くしようとしてこの実装になっているのか、それとも普通に実装したらこうなってしまっただけでもっと早くしてもいいのか、区別がつかない

>ISUCONのクローンを用意している状況となると、意図してこの状況にしている可能性があり、その可能性が排除できない以上、無駄な実装をせざるを得ないです。

>かといって、いちいち細かいところまで作問者に問い合わせるのも大変ですし、所詮は遊びでやっているので、自分の思ったとおりにやっています。

see: https://goryudyuma.hatenablog.jp/entry/2018/06/11/170711

ということが発生しており、参考実装を提供してくれる方が悩んでしまう状況になっているので、他言語で参考実装を作る時のガイドラインを作成する。

以下について記述するのが良さそう。
1. Ruby実装とGo実装の振れ幅ぐらいはOK
    * コードの見通しが変わってしまうのは仕方ないが、リクエストを受け取ってからレスポンスするまでの処理は原則変わらないようにする
1. 既存の参考実装に寄せるべきか、実装している言語の習慣に寄せるべきかを悩んだときには後者を優先する
1. 初期実装のベンチマーク(3並列)で N ~ M点に収まること。( [2] で後者に寄せることでM点を超えてしまう場合には、既存の実装に近づけること)
1. 判断が難しい部分はプルリクを投げる時に特にレビューしてもらいたい部分を記述する

**Comment by Goryudyuma** [comment]
3の点数の範囲ですが、

1. 点数の算出方法ですが、5回のベンチマークを行い、最高点と最低点を除いた三回の平均とする。これを「平均スコア」と呼ぶ。
2. まずは基準実装(←最初に実装されたRubyですかね？Goとかのほうがいいですかね？)で、「平均スコア」がN~M点に収まるハードウェアを用意する。
(AWSのインスタンスタイプなどで合わせてもよいが、検証のためにいちいち建ててベンチマークだけ取って壊して、ってやるのよりも、より汎用的になるかなと思いました。厳密にするなら検証環境用のAWSのレシピなどを用意すべきかもしれません。)
3. 新しく実装した参考実装の「平均スコア」が、基準の「平均スコア」の0.5~1.5倍(←要相談、範囲広いですかね？)の範囲に収まるようにした上でPullRequestを送る。

とかどうでしょう？

**Comment by showwin** [comment]
https://github.com/showwin/ISHOCON1/blob/main/CONTRIBUTING.md に明記したので close
